name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install requirements
      run: pip install --quiet -r requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,F231 *.py
        pylint --disable=C0301 --disable=C0326 *.py

    - name: Unit tests
      run: |
        python -m unittest --verbose --failfast